apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: network-bandwidth-annotation-manager
    app.kubernetes.io/version: 0.1.0
  name: nbam
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  labels:
    app.kubernetes.io/name: network-bandwidth-annotation-manager
    app.kubernetes.io/version: 0.1.0
  name: self-signed-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: network-bandwidth-annotation-manager
    app.kubernetes.io/version: 0.1.0
  name: network-bandwidth-annotation-manager
  namespace: nbam
spec:
  dnsNames:
    - network-bandwidth-annotation-manager.nbam.svc
    - network-bandwidth-annotation-manager.nbam.svc.cluster.local
  duration: 2160h
  isCA: false
  issuerRef:
    kind: ClusterIssuer
    name: self-signed-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 360h
  secretName: tls-network-bandwidth-annotation-manager
  subject:
    organizations:
      - NBAM
  usages:
    - server auth
    - client auth
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: network-bandwidth-annotation-manager
    app.kubernetes.io/version: 0.1.0
  name: network-bandwidth-annotation-manager-service-account
  namespace: nbam
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: network-bandwidth-annotation-manager
    app.kubernetes.io/version: 0.1.0
  name: network-bandwidth-annotation-manager-cluster-role
  namespace: nbam
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: network-bandwidth-annotation-manager
    app.kubernetes.io/version: 0.1.0
  name: network-bandwidth-annotation-manager
  namespace: nbam
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: network-bandwidth-annotation-manager-cluster-role
subjects:
  - kind: ServiceAccount
    name: network-bandwidth-annotation-manager-service-account
    namespace: nbam
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: network-bandwidth-annotation-manager
    app.kubernetes.io/version: 0.1.0
  name: network-bandwidth-annotation-manager
  namespace: nbam
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: network-bandwidth-annotation-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: network-bandwidth-annotation-manager
        app.kubernetes.io/version: 0.1.0
    spec:
      containers:
        - command:
            - ./network-bandwidth-annotation-manager
          env:
            - name: ADDR
              value: 0.0.0.0:8443
            - name: TLS_CERT
              value: /certs/tls.crt
            - name: TLS_KEY
              value: /certs/tls.key
          image: ghcr.io/thomask33/nbam:0.1.0
          name: network-bandwidth-annotation-manager
          ports:
            - containerPort: 8443
              name: https
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 12345
            runAsNonRoot: true
            runAsUser: 12345
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /certs
              name: tls-certs
              readOnly: true
      serviceAccountName: network-bandwidth-annotation-manager-service-account
      volumes:
        - name: tls-certs
          secret:
            secretName: tls-network-bandwidth-annotation-manager
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: network-bandwidth-annotation-manager
    app.kubernetes.io/version: 0.1.0
  name: network-bandwidth-annotation-manager
  namespace: nbam
spec:
  ports:
    - name: https
      port: 8443
  selector:
    app.kubernetes.io/name: network-bandwidth-annotation-manager
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: nbam/network-bandwidth-annotation-manager
  labels:
    app.kubernetes.io/name: network-bandwidth-annotation-manager
    app.kubernetes.io/version: 0.1.0
  name: network-bandwidth-annotation-manager
  namespace: nbam
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: network-bandwidth-annotation-manager
        namespace: nbam
        path: /annotate
        port: 8443
    failurePolicy: Ignore
    name: nbam-ns-annotate.nbam.svc
    namespaceSelector:
      matchLabels:
        nbam-mode: annotate
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
        scope: Namespaced
    sideEffects: None
    timeoutSeconds: 5
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: network-bandwidth-annotation-manager
        namespace: nbam
        path: /annotate
        port: 8443
    failurePolicy: Ignore
    name: nbam-object-annotate.nbam.svc
    objectSelector:
      matchLabels:
        nbam-mode: annotate
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
        scope: Namespaced
    sideEffects: None
    timeoutSeconds: 5
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: network-bandwidth-annotation-manager
        namespace: nbam
        path: /strip
        port: 8443
    failurePolicy: Ignore
    name: nbam-ns-strip.nbam.svc
    namespaceSelector:
      matchLabels:
        nbam-mode: strip
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
        scope: Namespaced
    sideEffects: None
    timeoutSeconds: 5
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: network-bandwidth-annotation-manager
        namespace: nbam
        path: /strip
        port: 8443
    failurePolicy: Ignore
    name: nbam-object-strip.nbam.svc
    objectSelector:
      matchLabels:
        nbam-mode: strip
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
        scope: Namespaced
    sideEffects: None
    timeoutSeconds: 5
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: network-bandwidth-annotation-manager
        namespace: nbam
        path: /overwrite
        port: 8443
    failurePolicy: Ignore
    name: nbam-ns-overwrite.nbam.svc
    namespaceSelector:
      matchLabels:
        nbam-mode: overwrite
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
        scope: Namespaced
    sideEffects: None
    timeoutSeconds: 5
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: network-bandwidth-annotation-manager
        namespace: nbam
        path: /overwrite
        port: 8443
    failurePolicy: Ignore
    name: nbam-object-overwrite.nbam.svc
    objectSelector:
      matchLabels:
        nbam-mode: overwrite
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
        scope: Namespaced
    sideEffects: None
    timeoutSeconds: 5
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: network-bandwidth-annotation-manager
        namespace: nbam
        path: /namespace
        port: 8443
    failurePolicy: Ignore
    name: nbam-ns-scheduler-override.nbam.svc
    namespaceSelector:
      matchExpressions:
        - key: nbam-default-scheduler
          operator: Exists
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
        scope: Namespaced
    sideEffects: None
    timeoutSeconds: 5
