apiVersion: v1
kind: Namespace
metadata:
  name: nbam
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signed-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: network-bandwidth-annotation-manager
  namespace: nbam
spec:
  dnsNames:
    - network-bandwidth-annotation-manager.nbam.svc
    - network-bandwidth-annotation-manager.nbam.svc.cluster.local
  duration: 2160h
  isCA: false
  issuerRef:
    kind: ClusterIssuer
    name: self-signed-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 360h
  secretName: tls-network-bandwidth-annotation-manager
  subject:
    organizations:
      - Thomas Kosiewski
  usages:
    - server auth
    - client auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-bandwidth-annotation-manager
  namespace: nbam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-bandwidth-annotation-manager
  template:
    metadata:
      labels:
        app: network-bandwidth-annotation-manager
    spec:
      containers:
        - command:
            - ./network-bandwidth-annotation-manager
            - -v
          env:
            - name: ADDR
              value: 0.0.0.0:8443
            - name: TLS_CERT
              value: /certs/tls.crt
            - name: TLS_KEY
              value: /certs/tls.key
          image: k3d-default-registry.localhost:9090/nbam:0.1.0
          imagePullPolicy: Always
          name: network-bandwidth-annotation-manager
          ports:
            - containerPort: 8443
              name: https
          volumeMounts:
            - mountPath: /certs
              name: tls-certs
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: tls-network-bandwidth-annotation-manager
---
apiVersion: v1
kind: Service
metadata:
  name: network-bandwidth-annotation-manager
  namespace: nbam
spec:
  ports:
    - name: https
      port: 8443
  selector:
    app: network-bandwidth-annotation-manager
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: nbam/network-bandwidth-annotation-manager
  name: network-bandwidth-annotation-manager
  namespace: nbam
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: network-bandwidth-annotation-manager
        namespace: nbam
        path: /mutate
        port: 8443
    failurePolicy: Ignore
    name: network-bandwidth-annotation-manager.nbam.svc
    namespaceSelector:
      matchLabels:
        nbam-enabled: "true"
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
        scope: Namespaced
    sideEffects: None
    timeoutSeconds: 5
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: network-bandwidth-annotation-manager
        namespace: nbam
        path: /mutate
        port: 8443
    failurePolicy: Ignore
    name: network-bandwidth-annotation-manager.nbam.svc
    objectSelector:
      matchLabels:
        nbam-enabled: "true"
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
        scope: Namespaced
    sideEffects: None
    timeoutSeconds: 5
