site_name: Network Bandwidth Annotation Manager

theme:
  name: material

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky

    - search.suggest
    - search.highlight
    - search.share

    - toc.follow

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

repo_url: https://github.com/ThomasK33/network-bandwidth-annotation-manager
edit_uri: edit/main/docs/

nav:
  - index.md
  - Features:
      - features/annotator-mode.md
      - features/overwrite-mode.md
      - features/strip-mode.md
      - features/scheduler-override.md
  - license.md

plugins:
  - roamlinks
  - search

markdown_extensions:
  - footnotes

  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
