apiVersion: v1
kind: Namespace
metadata:
  name: nbam-overwrite
  labels:
    nbam-mode: "overwrite"
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: nbam-overwrite
spec:
  containers:
    - name: my-container
      image: registry.k8s.io/pause:2.0
      resources:
        requests:
          cpu: 2
          networking.k8s.io/ingress-bandwidth: 1M
          networking.k8s.io/egress-bandwidth: 1M
        limits:
          cpu: 4
          # Limits the ingress bandwidth to 2Mbit/s
          networking.k8s.io/ingress-bandwidth: 2M
          # Limits the egress bandwidth to 2Mbit/s
          networking.k8s.io/egress-bandwidth: 2M
      # securityContext:
      #   allowPrivilegeEscalation: false
      #   capabilities:
      #     drop: ["ALL"]
      #   readOnlyRootFilesystem: true
      #   runAsNonRoot: true
      #   runAsUser: 12345
      #   runAsGroup: 12345
      #   seccompProfile:
      #     type: RuntimeDefault
