name: OCI

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Container Build Versions
        run: |
          go install github.com/tomwright/dasel/cmd/dasel@master

          echo VERSION=$(cat Cargo.toml | dasel -r toml 'package.version') >> $GITHUB_ENV

      - name: Login to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ThomasK33 --password-stdin

      - name: Build an image from Dockerfile
        run: docker build -t ghcr.io/thomask33/nbam:${{ env.VERSION }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ghcr.io/thomask33/nbam:${{ env.VERSION }}"
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"

      - name: Push image
        run: docker push ghcr.io/thomask33/nbam:${{ env.VERSION }}
